nixos: support boot with aarch64 image
netbootxyz/netboot.xyz pull request #1282
Opened 2023-09-05 08:57 UTC by 5aaee9

nixos-images has arm64 image since 23.05 release

2023-09-05 13:10 UTC, antonym commented on roles/netbootxyz/templates/menu/linux-arm.ipxe.j2
> +item nixos ${space} NixOS
Can we move this up to be alphabetical?

2023-09-05 13:11 UTC, antonym requested changes
Adjust menu entry

2023-09-06 04:40 UTC, 5aaee9 commented on roles/netbootxyz/templates/menu/linux-arm.ipxe.j2
> +item nixos ${space} NixOS
Updated

2023-09-06 06:19 UTC, antonym approved these changes

2023-09-06 09:35 UTC, merged