add Alpine Linux
netbootxyz/netboot.xyz pull request #223
Opened 2018-02-20 02:32 UTC by clandmeter

This is a first attempt of adding Alpine Linux to netboot.xyz.

We currently do not "officially" ship netboot images but this is high on my prio list. Instead I've added images for both x86 and x86_64 from both stable and edge releases to our dev server. I also have a few small patches ready to go into Alpine Linux to fix some corner cases which will be applied asap.

This has been tested with my custom [ipxe script ](https://github.com/clandmeter/netboot.xyz-custom/blob/master/custom.ipxe). Please check if i missed anything.

ref: #30

2018-02-21 18:27 UTC, antonym requested changes
This looks great so far, I tested it in VBox and it worked well.  I have a few comments and changes requested.

2018-02-21 18:27 UTC, antonym commented on src/alpinelinux.ipxe
> +# Alpine Linux netboot.xyz ipxe script.
Can just leave this as Alpine Linux to make it consistent with the other iPXE files.

2018-02-21 18:27 UTC, antonym commented on src/linux.ipxe
> +item alpinelinux ${space} Alpine Linux
Can we move it down to the All Others section and mark it as *Experimental*?

2018-02-21 18:27 UTC, antonym commented on src/alpinelinux.ipxe
> +set base-url http://dev.alpinelinux.org/~clandmeter/netboot/${version}/${bootarch}
I'm hesitant to add unofficial images but I'm ok with treating the distro as experimental as long as they are hosted from the alpinelinux.org domain.  If you can make progress on official images, we can remove the experimental tag and add signature checking for the images.  That way we can at least let the users experiment with the distro.

2018-02-21 19:54 UTC, clandmeter commented
All sounds good to me. I made the changes you requested.

Regarding the signatures, how frequent do you verify if the images are updated?
Is it possible users could have broken sigs if we update the images before you re-sign them?

2018-02-27 01:40 UTC, antonym commented
@clandmeter Thanks, looks good.  On the signatures, I currently try to avoid the releases that reside in a "rolling" directory and try and pull images or kernels from a location that is usually static and tagged as a release.  This way I don't have to worry about things breaking if there's a version bump which saves me having to chase things down quite a bit.  Currently the signature generation isn't the greatest and needs some rework but the script I use is here:

https://github.com/antonym/netboot.xyz-sigs/blob/master/generate-linux-sigs.sh

It goes and retrieves all of the latest kernels, signs them, and the keeps the signature files.  I plan on reworking the system into something a little less ghetto at some point, but it's a little fun to manage given the number of versions out there.

2018-03-16 22:41 UTC, antonym approved these changes

2018-03-16 22:53 UTC, antonym commented
Merging this in for now, but keep us updated on getting official builds.  Thanks!

2018-03-16 22:53 UTC, merged

2018-06-28 14:52 UTC, clandmeter commented
@antonym we now support netboot from repos since our latest release v3.8.

You can take a look at http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/

2018-06-28 14:54 UTC, antonym commented
Yep, saw that, will try and push up an update this week for it.  Thanks!