Update README.md
netbootxyz/netboot.xyz pull request #912
Opened 2021-06-11 09:38 UTC by berrydamien

cp: -r specified for directory

2021-06-11 17:09 UTC, antonym approved these changes

2021-06-11 17:11 UTC, antonym requested changes
Please make PR against development branch instead of master.

2021-06-14 06:53 UTC, berrydamien commented
> Please make PR against development branch instead of master.

done

2021-06-18 01:14 UTC, antonym commented
Added here: https://github.com/netbootxyz/netboot.xyz/commit/43e2f303def858974f47160e1b657385477e7a9f

2021-06-18 01:14 UTC, closed without merging